resolve deprecation warnings
-  controllers/publishingstrategy/publishingstrategy_controller_test.go:1069:46: cannot use testClient (variable of type *customClient) as "sigs.k8s.io/controller-runtime/pkg/client".Client value in struct literal: *customClient does not implement "sigs.k8s.io/controller-runtime/pkg/client".Client (wrong type for method Get)
-  main.go:111:3: SA1019: options.Namespace is deprecated: Use Cache.Namespaces instead. (staticcheck)
-  pkg/testutils/testutils.go:169:60: SA1019: pointer.StringPtr is deprecated: Use String instead. (staticcheck)

Signed-off-by: Brady Pratt <bpratt@redhat.com>